native coin transfer event log
ROIchain/coreth pull request #4
Opened 2021-12-18 18:03 UTC by diepmv

2021-12-19 06:23 UTC, Zergity requested changes

2021-12-19 06:23 UTC, Zergity commented on core/vm/evm.go
> +		Address:     common.HexToAddress("0x0000000000000000000000000000000000000000"),
please use `common.Address{}` instead of `common.HexToAddress("0x0000000000000000000000000000000000000000")`

2021-12-19 06:23 UTC, Zergity commented on core/vm/evm.go
> +	topics[0] = common.HexToHash("0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef")
this hash can be created as a global var/const to be reused

2021-12-19 06:23 UTC, Zergity commented on core/vm/evm.go
> +		BlockNumber: evm.Context.BlockNumber.Uint64(),
`BlockNumber` is not required here, read the `Log` struct for each field description

2021-12-19 06:23 UTC, Zergity commented on core/vm/evm.go
>  	evm.Context.Transfer(evm.StateDB, caller.Address(), addr, value)
there are other calls to `evm.Context.Transfer`, they must also generate the log, please move the AddLog code to inside the `Transfer` function

2021-12-21 11:48 UTC, enixdark commented
@Zergity ze please review this issue.
@diepmv any problem ?

2021-12-21 12:47 UTC, diepmv commented
> @Zergity ze please review this issue. @diepmv any problem, if solved, please comment in here or directly to issue comment above ?

2021-12-21 12:50 UTC, Zergity commented
> > @Zergity ze please review this issue. @diepmv any problem, if solved, please comment in here or directly to issue comment above ?
> 
> @enixdark no problem, @Zergity help me review this issue.

I got this, I will review all PRs when I finish the feature_test frame. Please proceed to the next issue, if you will.

2021-12-22 14:45 UTC, Zergity approved these changes

2021-12-22 14:45 UTC, merged