batch transaction
ROIchain/coreth pull request #6
Opened 2021-12-31 02:26 UTC by diepmv

2021-12-31 02:27 UTC, diepmv commented
@Zergity help me review my test version

2021-12-31 09:15 UTC, Zergity requested changes
this logic should be applied in `func (st *StateTransition) TransitionDb()`, and only this specific line is need to called for each inner tx:

`ret, st.gas, vmerr = st.evm.Call(sender, st.to(), st.data, st.gas, st.value)`

2021-12-31 09:15 UTC, Zergity commented on core/vm/evm.go
> +	BADDR              = common.HexToAddress("0x5555555555555555555555555555555555555555")
this address is already declare somewhere else, please search for it

2021-12-31 09:15 UTC, Zergity commented on core/vm/evm.go
> +		txs, _ = decodeBatchTxInput(input)
don't ignore error here, this part should be more defensive: if the decode is not success, fallback to legacy tx

2021-12-31 09:26 UTC, Zergity commented
> `ret, st.gas, vmerr = st.evm.Call(sender, st.to(), st.data, st.gas, st.value)`

```
if contractCreation {
	ret, _, st.gas, vmerr = st.evm.Create(sender, st.data, st.gas, st.value)
} else {
	// Increment the nonce for the next transaction
	st.state.SetNonce(msg.From(), st.state.GetNonce(sender.Address())+1)
	if isBatch {
		var rets [][]byte
		for each txs {
			ret, st.gas, vmerr = st.evm.Call(sender, st.to(), st.data, st.gas, st.value)
			if vmerr != nil {
				break	// stop on the first error
			}
			rets.push(ret)
		}
		if vmerr == nil {
			ret = encodeRetsHere(rets)
		}
	} else {
		ret, st.gas, vmerr = st.evm.Call(sender, st.to(), st.data, st.gas, st.value)
	}
}
```

2022-01-01 14:54 UTC, diepmv commented
@Zergity @enixdark help me review

2022-01-04 03:31 UTC, Zergity requested changes

2022-01-04 03:31 UTC, Zergity commented on core/state_transition.go
> +			snapshot := st.evm.StateDB.Snapshot()
only create snapshot after `var rets [][]byte`

2022-01-04 03:31 UTC, Zergity commented on core/state_transition.go
> +		if isBatchTx(st.to(), st.data) {
`isBatchTx` and `decodeBatchTxInput` should be merged into one (`decodeBatchTx`) to simplify the if-else flow here

2022-01-04 03:31 UTC, Zergity commented on core/state_transition.go
> +				ret, _ = encodeBatchTxOutput(rets)
as my comment for this, we only `encodeBatchTxOutput` when `vmerr == nil`. The test case is: send a batch tx of 3 tx, with the second tx failed, the result of the batch tx must be the revert reason of the failed tx.

2022-01-04 03:31 UTC, Zergity commented on core/state_transition.go
> +	batchAbi, err := abi.JSON(strings.NewReader(batchTxAbiJson))
please don't parse the JSON from text each time this method is called, create an `abi.ABI` struct contact for this

2022-01-05 02:20 UTC, diepmv commented on core/state_transition.go
> +			snapshot := st.evm.StateDB.Snapshot()
fixed

2022-01-05 02:20 UTC, diepmv commented on core/state_transition.go
> +		if isBatchTx(st.to(), st.data) {
fixed

2022-01-05 02:20 UTC, diepmv commented on core/state_transition.go
> +				ret, _ = encodeBatchTxOutput(rets)
fixed

2022-01-05 02:20 UTC, diepmv commented on core/state_transition.go
> +	batchAbi, err := abi.JSON(strings.NewReader(batchTxAbiJson))
fixed

2022-01-07 02:23 UTC, Zergity requested changes

2022-01-07 02:23 UTC, Zergity commented on core/state_transition.go
> +func encodeBatchTxOutput(data [][]byte) ([]byte, error) {
I've added a commit in feature-tests PR, to test a high-level call and return value encode, please make sure it work with any return values.

[766925a475395064f1f9d2d9f82b6f89e1e124a3](https://github.com/ROIchain/feature-tests/pull/2/commits/766925a475395064f1f9d2d9f82b6f89e1e124a3)

2022-01-10 17:13 UTC, diepmv commented on core/state_transition.go
> +func decodeBatchTx(addr common.Address, encodedData []byte) (batchTx bool, txs []*Tx, err error) {
fixed

2022-01-12 13:01 UTC, Zergity requested changes
some return type is tightly packed by solidity, which is unptedictable from the evm view. please modify the code to return only the last tx result, instead of encoding all of them

2022-01-14 15:20 UTC, Zergity approved these changes
please add the gasLimit tests for features test and it's good to go

2022-01-16 05:10 UTC, merged